name: dmdlab_qrscanner
description: QR Scanner — DMD Lab
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # QR Scan
  mobile_scanner: ^6.0.0

  # State management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^14.0.0

  # Storage
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4

  # Fonts
  google_fonts: ^6.2.1

  # Utils
  url_launcher: ^6.3.1
  share_plus: ^10.1.2
  shared_preferences: ^2.3.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # Fonts gérées via google_fonts

# --- Icône d'app ---
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/qrscanner_logo_white.png"
  adaptive_icon_background: "#6366F1"
  adaptive_icon_foreground: "assets/images/qrscanner_logo_white.png"
  min_sdk_android: 21
  web:
    generate: false

# --- Splash screen natif ---
flutter_native_splash:
  color: "#6366F1"
  color_dark: "#6366F1"
  image: assets/images/qrscanner_logo_white.png
  android_12:
    color: "#6366F1"
    image: assets/images/qrscanner_logo_white.png
  fullscreen: false
